[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/certificado/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/ValidacionQr"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/ValidacionCertificados"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data: blob: *; font-src 'self' https: data: *; connect-src 'self' https: wss: *; frame-ancestors 'none'; form-action 'self'; upgrade-insecure-requests;"
    Referrer-Policy = "strict-origin-when-cross-origin"